# permissions for end users to edit pgadmins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pgadmin-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pgadmin-operator
    app.kubernetes.io/part-of: pgadmin-operator
    app.kubernetes.io/managed-by: kustomize
  name: pgadmin-editor-role
rules:
- apiGroups:
  - pgadmin.dhope-nagesh.io
  resources:
  - pgadmins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pgadmin.dhope-nagesh.io
  resources:
  - pgadmins/status
  verbs:
  - get
